### ISSUE TITLE
Kanban and Setup 

### ISSUE THREAD

**Issue by angelacuahutle** [fabianomag/space-travelers#24]
Dear Reviewer, 

We have covered the first card from the Kanban project: 
Create basic structure for Missions - Setup #20 which involves the following tasks:

- Create a route and a view component. Use <NavLink /> for the page navigation links and style active class to indicate which section/page the user is currently on (underline active navigation link).
- Create a directory for all Redux state slice files.

https://github.com/fabianofrank/space-travelers/projects/1

Thanks!

**Comment by TedLivist** [comment]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @angelacuahutle and @fabianofrank,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted an Issue that does not contain the number of people working on the project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by fabianofrank** [comment]
Dear Reviewer, 

Team: @fabianofrank & @angelacuahutle 

We have covered the first card from the Kanban project: 
Create basic structure for Missions - Setup #20 which involves the following tasks:

- Create a route and a view component. Use <NavLink /> for the page navigation links and style active class to indicate which section/page the user is currently on (underline active navigation link).
- Create a directory for all Redux state slice files.

https://github.com/fabianofrank/space-travelers/projects/1

Thanks!

**Comment by rloterh** [comment]
## Status: Approved :heavy_check_mark:

Hello Team,  

This task is complete! Great job 🥇. There is nothing else to say other than... it's time to proceed with the next task/ project 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Board correctly setup
- Issues well created with appropriate info
- Discussion and collaboration were well observed
- Fiar distribution of tasks among team
- Good description of tasks 

<br>
Cheers...and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
